### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [purwar2016/ArduinoBlue-library#3]
Hi @jaean123     

we have detected a discrepancy in the library name written inside `library.properties`
  `ArduinoCommander`
and the library name written inside inside the library manager index:
  `Arduino Commander`

I think this is due to an error on our side when the library was registered in the library manager index (at the times this process was mostly manual).

Now we are about to introduce a change in the library manager that forbids the situation described above and the releases whose name differs from the name registered in the library index are ignored.

Is it ok for you to use the name `ArduinoCommander`? If yes, the library will be re-published with the name `ArduinoCommander` and the old `Arduino Commander` will be removed from the index, in this case no action is needed on your side. In absence of an answer from you we will proceed with this proposal next week.

Thanks

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 1033 - 2018/01/15 15:44:51 Scraping https://github.com/jaean123/ArduinoBLE-library.git
JOB 1033 - 2018/01/15 15:44:51 Checking out tag: 1.0
JOB 1033 - 2018/01/15 15:44:52 Release ArduinoCommander:1.0.0 has wrong library name, should be Arduino Commander
```

**Comment by jaean123** [comment]
Yes I'm renaming my library. Please make the necessary changes. Thanks.

**Comment by jaean123** [comment]
Actually I recently changed the name to "ArduinoBLE" which will be the permanent name.
Please make the necessary changes. Thanks.

**Comment by cmaglie** [comment]
Since you're changing, may I ask you to consider another name? `ArduinoBLE` looks like a library made by Arduino (the company).

Something like `SimpleBLE` or `BLEController`?

**Comment by jaean123** [comment]
If possible, I prefer to keep ArduinoBLE since that's the name of the app in the Play store.
If not, I can change it to SimpleBLE. Please let me know.

**Comment by cmaglie** [comment]
Ok, whatever the name, you should:

1) fix the `library.properties`, commit and push
2) update the release/tag **after** doing 1. (in other words remove the old tag/release and re-do it) so I can update the name on the indexer.

I'll pick the name from here:

https://github.com/jaean123/ArduinoBlue-library/blob/1.0/library.properties

please note that the tag `1.0` still has the old library.properties because the tag has been created on an old commit.
