### ISSUE TITLE
isConnected() does not appear to work, always reports not connected

### ISSUE THREAD

**Issue by ct6502** [purwar2016/ArduinoBlue-library#4]
I'm using ArduinoBlue library version 2.1.0, with the ArduinoBlue iPhone app version 2.1.1, and a DSD HM10 bluetooth module. The isConnected() method never seems to return "true", even when the phone is connected. All of the other methods work fine - I can get buttons, text, sliders, etc. Here is a sample Arduino script which shows the issue:

```
#include <SoftwareSerial.h>
#include <ArduinoBlue.h>
SoftwareSerial bluetooth(A2, A3);
ArduinoBlue phone(bluetooth);

void setup() {
    Serial.begin(9600);
    bluetooth.begin(9600);
    delay(100);
    Serial.println("setup complete");
}
void loop() {
  if (phone.isConnected()) {
    Serial.println("ArduinoBlue connected");
  } else {
    Serial.println("ArduinoBlue NOT connected");
  }
  delay(1000);
}
```

Using the serial console, it always shows "not connected". Thanks!

**Comment by jaean123** [comment]
Thank you for letting me know.
I'll take a look at this for the next update.

**Comment by jaean123** [comment]
It might be a while until a next update is released due to time constraints.
Meanwhile, you can check the STATE pin, which I think it's connected to the red LED. 
You know that it's connected when the STATE pin is steady.
Sorry for the late reply

**Comment by ct6502** [comment]
Unfortunately, I'm using an HM10 that doesn't have the STATE pin. It just has VCC, GND, RX, and TX. I'm also trying to conserve the other Arduino pins so I don't really want to tie up another one. But thanks for the suggestion!

**Comment by jaean123** [comment]
IsConnected method is no longer a planned feature. The only way to find out if the HM10 is connected is by using the STATE pin.
I apologize for any inconvenience this may cause.
