### ISSUE TITLE
FunctionType.h is missing...

### ISSUE THREAD

**Issue by SingingEngineer** [purwar2016/ArduinoBlue-library#5]
I've been using your previous version for the past month and it has been amazing!  However, I just updated to the 3.0 version on my iPhone and loaded the new Arduino library and when i try to compile it, I receive this error...  Can you please help?

C:\Users\100330784\Documents\Arduino\libraries\ArduinoBlue\src/ArduinoBlue.h:9:26: fatal error: FunctionType.h: No such file or directory

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by jaean123** [comment]
I’m working on fixing this. I’ll update it soon.
Thank you for informing.

**Comment by jaean123** [comment]
Fixed. You can download the latest release 3.0.1.
It may take a while before the Arduino library manager will see the update.

**Comment by SingingEngineer** [comment]
Thank you!
